services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: agenda
      MONGODB_DATABASE: agenda
    volumes: 
      - db_data:/data/db
    networks:
      - agenda-network

  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: unless-stopped
    ports:
      - "8888:8081"
    links:
      - mongo
    networks:
      - agenda-network
  backend: 
    container_name: agenda-backend
    hostname: agenda-backend
    restart: unless-stopped
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:  
      DB_SERVER: mongo
      DB_NAME: agenda
      SERVER_ADDRESS: 0.0.0.0:8081
      PROMETHEUS_SERVER: http://prometheus:9090/
    ports:
      - 8081:8081
    links:
      - mongo
    networks:
      - agenda-network


volumes:
    db_data:

networks: 
    agenda-network:
      driver: bridge