spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_URL:127.0.0.1:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: ${KAFKA_GROUP_ID:group_id}
app:
  topic:
    users: ${KAFKA_TOPIC:USERS_CREATION}
